"""empty message

Revision ID: b502ee0333ad
Revises: 6058d2b9524c
Create Date: 2021-06-11 21:07:10.589612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b502ee0333ad'
down_revision = '6058d2b9524c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questoes', sa.Column('opcaoA', sa.String(length=500), nullable=True))
    op.add_column('questoes', sa.Column('opcaoB', sa.String(length=500), nullable=True))
    op.add_column('questoes', sa.Column('opcaoC', sa.String(length=500), nullable=True))
    op.add_column('questoes', sa.Column('opcaoD', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questoes', 'opcaoD')
    op.drop_column('questoes', 'opcaoC')
    op.drop_column('questoes', 'opcaoB')
    op.drop_column('questoes', 'opcaoA')
    # ### end Alembic commands ###
