"""empty message

Revision ID: db48ee48a726
Revises: 
Create Date: 2021-06-12 05:14:23.851416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db48ee48a726'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questoes',
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('pergunta', sa.String(length=500), nullable=True),
    sa.Column('opcaoA', sa.String(length=500), nullable=True),
    sa.Column('opcaoB', sa.String(length=500), nullable=True),
    sa.Column('opcaoC', sa.String(length=500), nullable=True),
    sa.Column('opcaoD', sa.String(length=500), nullable=True),
    sa.Column('resposta', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questoes')
    # ### end Alembic commands ###
